project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"

website:
  title: "Exam Questions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Answer Key
        href: about.qmd

format:
  html:
    theme:
      light: [flatly]
    css: 
      - styles.css
    toc: true

editor: visual

